
[Settings]
fNPCHideLightLevelThreshold = 30.0
fStressIncrease = 15.0
iNPCHideThreshold = 50
fLightLevelThreshold = 80.0
fSecondsTillStress = 30.0
fNPCHideDistanceFullFade = 2400.0
fNPCHideDistanceNoFade = 1200.0

[Toggles]
bAllowDarknessChange = true
bEnableSneakLevels = false
bNoVampWere = false
bEnableNightEyeImmunity = false
bHideNPCsInDark = true

[Text]
sStressMessage = "The darkness here is overwhelming..."